version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    open-pull-requests-limit: 10
    versioning-strategy: increase

    schedule:
      interval: daily
      time: "07:00"
      timezone: Asia/Jakarta

    assignees:
      - manferlo81

    groups:
      lint:
        dependency-type: development
        patterns:
          - eslint
          - globals
          - typescript-eslint
          - "@eslint/*"
          - "@*/eslint-plugin"
          - eslint-plugin-*
          - eslint-*

      types:
        dependency-type: development
        patterns:
          - "@types/*"

      test:
        dependency-type: development
        patterns:
          - jest
          - ts-jest

      babel:
        dependency-type: development
        patterns:
          - "@babel"
          - core-js

      others:
        dependency-type: development
        patterns:
          - husky
          - npm-run-all
          - rimraf
          - chokidar
