version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    open-pull-requests-limit: 10
    versioning-strategy: increase

    schedule:
      interval: daily
      time: "07:00"
      timezone: Asia/Jakarta

    assignees:
      - manferlo81
